service: ohcrud

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-2
  memorySize: 128
  timeout: 30
  environment:
    # You need to set up a .env.yaml file of your own with your app password in it
    DB_HOST: ${file(./.env.yml):DB_HOST}
    DB_PASS: ${file(./.env.yml):DB_PASS}
    DB_USER: ${file(./.env.yml):DB_USER}
    DB_NAME: ${file(./.env.yml):DB_NAME}
  apiKeys:
    - todoAPI


plugins:
  - serverless-offline

package:
  include:
  - features/**
  - models/**

functions:
  getTodo:
    handler: features/read.getTodo
    events:
      - http:
          path: todo/{id}
          method: get
          private: true

  listTodos:
    handler: features/read.listTodos
    events:
      - http:
          path: todos
          method: get

  createTodo:
    handler: features/create.createTodo
    events:
      - http:
          path: todo
          method: post
          private: true

  deleteTodo:
    handler: features/delete.deleteTodo
    events:
      - http:
          path: todo/{id}
          method: delete
          private: true

  updateTodo:
    handler: features/update.updateTodo
    events:
      - http:
          path: todo/{id}
          method: patch
          private: true
